### ISSUE TITLE
add Google Analytics integration to template

### ISSUE THREAD

**Issue by msalganik** [open-review-toolkit/open-review-toolkit#12]

**Comment by lukebaker** [comment]
@msalganik This is already in the template with a dummy code. It would be updated here: https://github.com/open-review-toolkit/open-review-toolkit/blob/e91b8a045447e1ffac4450edbcc0494f43c0375d/website/config.rb#L14

**Comment by msalganik** [comment]
Great.  I'm closing this issue.
