### ISSUE TITLE
expand readme about VM

### ISSUE THREAD

**Issue by msalganik** [open-review-toolkit/open-review-toolkit#13]
@lukebaker 

Can you add a bit more information about this step?

"From your terminal, run: vagrant up. The very first time you run this command it will download roughly 1.5GB of data, so it may take a few minutes or more depending on the speed of your internet connection."

Perhaps we could explain what this 1.5GB file is and link to the other repo?

**Comment by lukebaker** [comment]
@msalganik I'm worried that linking to the other repo at this point in the documentation may be confusing. I did update it to include mention of the virtual machine image in 6bcc733

**Comment by msalganik** [comment]
OK, but we are asking people to download a huge image and many authors have not used a VM before so they will find it strange.  Maybe we could add a section to the readme about the VM and what is in it and link to the other repo?

**Comment by lukebaker** [comment]
In 139a3c6295 and 171cbef6d, I've added a couple more additions that attempt to clearly indicate that the virtual machine is what they'll be downloading and a link to the vagrant-build repository. Does that look good?

**Comment by msalganik** [comment]
Great.  I fixed one typo in the first sentence: https://github.com/open-review-toolkit/open-review-toolkit/commit/f95dd16182f828d26a3246f066597512eff41574

I think this issue is resolved.  If you agree, please close it.
