### ISSUE TITLE
Create first official release

### ISSUE THREAD

**Issue by lukebaker** [open-review-toolkit/open-review-toolkit#14]
@msalganik, I think the last step here is to create the first official release. Either of us can do that here: https://github.com/open-review-toolkit/open-review-toolkit/releases/new

If you'd like me to take care of it, let me know when we're ready to do that.

**Comment by msalganik** [comment]
Great.  You can create the release.  And, let's keep documenting the changes between releases.  Do you think the system you are using now the one that we should keep using?  It seems reasonable to me, but I'm open to whatever you think is best.

**Comment by lukebaker** [comment]
All set: https://github.com/open-review-toolkit/open-review-toolkit/releases/tag/v0.1
