### ISSUE TITLE
Add tests for verifying the rendered styles of certain elements

### ISSUE THREAD

**Issue by lukebaker** [open-review-toolkit/open-review-toolkit#15]
Recent changes (a637a5f90d2937d78521ea2fddbae66d1e82fb66, e493245f58302a443ecb6b809eab4d4ff2064549, 59e7b0e503cd9ae75466649e4a4c54694f0a6616, 639e60abc37f46237aff84d6383ccf3697c461b1) to block quote styles and list styles had some regressions that would be good to have tests for.

- [x] Table of contents lists should not have bottom margin.
- [x] Lists within the book contents should have bottom margin.
- [x] Lists and paragraphs inside blockquotes should not have bottom margin.

**Comment by msalganik** [comment]
Great.  Thanks.  Is this the kind of thing where we can have a badge now? https://docs.travis-ci.com/user/status-images/

And, does this mean that we should update our FAQ (https://github.com/open-review-toolkit/open-review-toolkit/wiki/FAQ) as part of building out the documentation?

**Comment by lukebaker** [comment]
> Great. Thanks. Is this the kind of thing where we can have a badge now? https://docs.travis-ci.com/user/status-images/

I've added the badge to the README.

> And, does this mean that we should update our FAQ (https://github.com/open-review-toolkit/open-review-toolkit/wiki/FAQ) as part of building out the documentation?

I've added a FAQ about where to find the tests.

**Comment by msalganik** [comment]
Great.  Thanks.
