### ISSUE TITLE
full table of contents not accessible on all screens size

### ISSUE THREAD

**Issue by aritari** [open-review-toolkit/open-review-toolkit#22]
On screens where the height is insufficient to keep the entire TOC visible, there is no way to scroll to the below the fold. Adding a scrollbar to the TOC section would resolve this.

**Comment by lukebaker** [comment]
@msalganik, this issue is not a problem in Open Review Toolkit as the design of it and Bit By Bit's site has diverged. However, this issue is now fixed on the Bit By Bit site.

http://www.bitbybitbook.com/en/asking-questions/total-survey-error/

**Comment by msalganik** [comment]
👍
