### ISSUE TITLE
software dependencies should all be updated to current releases and rebuild

### ISSUE THREAD

**Issue by aritari** [open-review-toolkit/open-review-toolkit#24]
"when we release v 1.0 of the Open Review Toolkit I want to make sure that it is using the newest version of pandoc, latex, R, etc"

**Comment by lukebaker** [comment]
@msalganik As of #30 (released as [v0.2.0](https://github.com/open-review-toolkit/open-review-toolkit/releases/tag/v0.2.0)), I made upgraded Pandoc from 1.17.2 to 1.19.2.4. As part of that, I upgraded the other Pandoc related software to the highest version that supports 1.19.2.4. I also upgraded Ruby to 2.4.4. These upgrades match the versions we used for the 1st edition of _Bit by Bit_.

Earlier in the _Bit by Bit_ process I had attempted some higher upgrades of Pandoc but ran into issues with the other Pandoc related software not supporting the most recent release of Pandoc and the HTML markup that Pandoc created had changed enough to require some additional changes on our end.

Are you interested in me seeing how high of a version of Pandoc we can use for Open Review Toolkit and use that, even if it exceeds what we've used for _Bit by Bit_?

**Comment by msalganik** [comment]
Thanks @lukebaker.   While you are thinking about it, I think it makes sense to see if we can go from pandoc 1.19.24 to pandoc 2.X.   I think that would make maintenance easier.  Do you want to try a bit?  If it turns out to be too hard we can stop.  Also, if you know which parts are causing problems I might have ideas about how to help (or maybe not).

**Comment by lukebaker** [comment]
@msalganik, I've deployed a [new version](https://github.com/open-review-toolkit/open-review-toolkit/releases/tag/v0.3.0) of Open Review Toolkit that uses Pandoc 2.2.

**Comment by msalganik** [comment]
Thanks @lukebaker
