### ISSUE TITLE
Consider uploading provisioned box to Vagrant's Atlas

### ISSUE THREAD

**Issue by lukebaker** [open-review-toolkit/open-review-toolkit#3]
Instead of having everyone download a bare-bones Ubuntu box and then provision it on their own, we might be better off providing a box that has been pre-provisioned. In other words, they should be able to simply download this box (which would happen automatically with `vagrant up`) and then get going. It would reduce the chances of errors during provision and significantly reduce the amount of time that they need to wait as currently provisioning takes quite awhile.

If we go this route, we'll likely move all provisioning recipes to a separate repo which would deal with downloading base box, provisioning, and uploading the created box.

**Comment by lukebaker** [comment]
I investigated this a bit, so I'll document what I found. If we go this route, it'd be nice if we could upload our  Vagrant box to the [public Vagrant repository of boxes](https://atlas.hashicorp.com/boxes/search). It looks like to do this, we need to create either a single user account for open-review-toolkit or [creating separate user accounts](https://atlas.hashicorp.com/account/new) and then [creating an organization account for open-review-toolkit](https://atlas.hashicorp.com/help/organizations/create).

In terms of priority, I'd put this somewhere above nice to have and below required for the beta. I'm hoping we have time to sort this out once we have the rest in place.

**Comment by lukebaker** [comment]
I went ahead and created an open-review-toolkit organization and added a Vagrant box to it called 'open-review-toolkit'. Matt, your @princeton.edu email address is associated with the organization.

**Comment by lukebaker** [comment]
The Vagrant box is here: https://atlas.hashicorp.com/open-review-toolkit/boxes/open-review-toolkit

**Comment by msalganik** [comment]
Great.  Thanks @lukebaker
