### ISSUE TITLE
To support the other languages, such as Chinese

### ISSUE THREAD

**Issue by chengjun** [open-review-toolkit/open-review-toolkit#35]
I would like to thank the developers for providing a such great open source software for writing open access books. However, I encounter a problem for writing Chinese. For example, if I write Chinese `in the first level title` , the other parts of the book would not appear. Any suggestion is welcome.

**Comment by lukebaker** [comment]
Thanks for this report.

Could you confirm for me that this issue only occurs with running `make book` to create the PDF and not when running `make site`? In my testing, I think `make site` works correctly but the PDF generation needs some fixes.

**Comment by chengjun** [comment]
This issue occurs when I am running `make site`. I have not tested `make book` yet.

**Comment by lukebaker** [comment]
> This issue occurs when I am running make site. I have not tested make book yet.

That sounds different from what I'm seeing. Could you attach a sample markdown file that exhibits the behavior you see and any error messages that you see? Thanks!

**Comment by chengjun** [comment]
Sure. Thank you very much. Attached is a markdown file for test. Since I can't upload is as a markdown file, I zip it as following, and you can unzip it for test. 

[_01-frontpage.md.zip](https://github.com/open-review-toolkit/open-review-toolkit/files/2522590/_01-frontpage.md.zip)


```
# 首页 {.unnumbered}

\adjustmtc

This page is for test.
```

You can also see an online example here: https://ccrbook.github.io/ . And you can notice that the other sections of the book will not show up.

**Comment by lukebaker** [comment]
@chengjun I've created a new release (v0.3.1), which contains the fixes for this issue that you reported. If you update to v0.3.1, you will need to re-create the Vagrant environment with by running `vagrant destroy` and then `vagrant up`.

**Comment by chengjun** [comment]
Thank you a lot for your generous help.
