### ISSUE TITLE
Setup sample.openreviewtoolkit.org

### ISSUE THREAD

**Issue by lukebaker** [open-review-toolkit/open-review-toolkit#4]
@msalganik, I propose we setup sample.openreviewtoolkit.org to showcase the site that gets created via the sample book that we're going to create in this repo. I figure we might as well set this up now, so that we can use it as we flesh out this beta. You're welcome to use a different domain / sub-domain, but I expect this will be different from the primary site for the Open Review Toolkit.

I believe the DNS for this sub-domain should match www.bitbybitbook.com as we'll host it on GitHub Pages. Sound good?

**Comment by lukebaker** [comment]
> I believe the DNS for this sub-domain should match www.bitbybitbook.com as we'll host it on GitHub Pages.

Actually, I think when we setup www.bitbybitbook.com, we created a CNAME record pointing at `msalganik.github.io`, whereas for sample.openreviewtoolkit.org we should use `open-review-toolkit.github.io`. We can do this over Skype if you'd prefer.

**Comment by msalganik** [comment]
@lukebaker I like this idea (showing a sample webpage created by our template), but I don't understand all the issues here.  I'll email you about setting up a skype now that I have all the domain names.

**Comment by lukebaker** [comment]
This is all set: http://sample.openreviewtoolkit.org/
