### ISSUE TITLE
Update Travis CI to also push generate site to GitHub Pages

### ISSUE THREAD

**Issue by lukebaker** [open-review-toolkit/open-review-toolkit#6]
When Travis CI runs on the master branch, it should automatically push the generated site to GitHub Pages.

**Comment by lukebaker** [comment]
This is all set, though the site doesn't quite work yet as it doesn't have its own domain. The site expects to be at it's own domain rather than residing within a sub-directory. Once we handle #4, we should be all set.

For now: https://open-review-toolkit.github.io/open-review-toolkit

**Comment by msalganik** [comment]
Cool.  I like this idea.
