### ISSUE TITLE
Install nginx to serve build directory

### ISSUE THREAD

**Issue by lukebaker** [open-review-toolkit/open-review-toolkit#8]
Inside the Vagrant VM, we want to run nginx to serve the build directory. This way someone, can run `make site` and then view it in their local browser.

**Comment by lukebaker** [comment]
This is all set with the work done in the [vagrant-build repo](https://github.com/open-review-toolkit/vagrant-build).

**Comment by msalganik** [comment]
Great.  Thanks @lukebaker
